<?php

return [
    'assets' => [
        'path' => 'assets/modules/evo-ui',
    ],
    'theme' => [
        'themes' => ['evolight', 'evolightness', 'evodark', 'evodarkness'],
        'light_themes' => ['evolight', 'evolightness'],
        'dark_themes' => ['evodark', 'evodarkness'],
        'default_light' => 'evolight',
        'default_dark' => 'evodark',
        'manager_modes' => ['', 'lightness', 'light', 'dark', 'darkness'],
    ],
    'livewire' => [
        'layout' => 'evo::layouts.manager',
    ],
    'multilingual' => [
        'enabled' => 'auto',
        'provider' => 'sLang',
        'locales' => [],
        'resource_fields' => ['pagetitle', 'longtitle', 'description', 'introtext', 'content', 'menutitle', 'seotitle', 'seodescription'],
        'tvs' => [],
    ],
    'tables' => [
        'site_content' => [
            'model' => \EvolutionCMS\Models\SiteContent::class,
            'with' => ['tpl'],
            'where' => [
                ['deleted', 0],
            ],
            'order_by' => [
                ['parent'],
                ['menuindex'],
                ['id'],
            ],
            'per_page' => 5,
            'per_page_options' => [5, 10, 20, 50, 100],
            'enabled_columns' => ['id', 'pagetitle', 'template', 'publishedon'],
            'enabled_filters' => ['templates', 'publishedon_range', 'kind', 'published'],
            'selectable' => true,
            'views' => ['table', 'list'],
            'default_view' => 'table',
            'search' => [
                'fields' => ['pagetitle', 'alias', 'id'],
            ],
            'actions' => [
                ['icon' => 'plus', 'label' => 'evo::global.action_add', 'url' => '?a=4', 'tone' => 'success', 'permission' => 'new_document'],
                ['icon' => 'pencil', 'label' => 'evo::global.action_edit', 'url' => '?a=27&id={id}', 'selection' => 'single', 'tone' => 'primary', 'permission' => 'edit_document'],
                ['icon' => 'copy', 'label' => 'evo::global.action_copy', 'url' => '?a=94&id={id}', 'selection' => 'single', 'tone' => 'info', 'permission' => 'new_document'],
                ['icon' => 'trash', 'label' => 'evo::global.action_delete', 'url' => '?a=6&id={id}', 'selection' => 'single', 'tone' => 'danger', 'permission' => 'delete_document'],
            ],
            'filters' => [
                [
                    'type' => 'multi-select',
                    'state' => 'templates',
                    'field' => 'template',
                    'icon' => 'template',
                    'label' => 'evo::global.filter_templates',
                    'search_label' => 'evo::global.filter_templates_search',
                    'options_source' => [
                        'model' => \EvolutionCMS\Models\SiteTemplate::class,
                        'value' => 'id',
                        'label' => 'templatename',
                        'order_by' => [['templatename']],
                    ],
                ],
                [
                    'type' => 'date-range',
                    'state' => 'publishedon_range',
                    'field' => 'publishedon',
                    'icon' => 'calendar',
                    'label' => 'evo::global.filter_publication_date',
                    'default' => ['from' => '', 'to' => ''],
                ],
                [
                    'type' => 'segmented',
                    'state' => 'kind',
                    'default' => 'all',
                    'label' => 'evo::global.filter_kind',
                    'options' => [
                        ['value' => 'all', 'icon' => 'list', 'label' => 'evo::global.kind_all'],
                        ['value' => 'folders', 'icon' => 'folder', 'label' => 'evo::global.kind_folders', 'where' => [['isfolder', 1]]],
                        ['value' => 'documents', 'icon' => 'file-text', 'label' => 'evo::global.kind_documents', 'where' => [['isfolder', 0]]],
                    ],
                ],
                [
                    'type' => 'segmented',
                    'state' => 'published',
                    'default' => 'all',
                    'label' => 'evo::global.filter_published',
                    'options' => [
                        ['value' => 'all', 'icon' => 'circle-dashed', 'label' => 'evo::global.kind_all'],
                        ['value' => 'published', 'icon' => 'eye', 'label' => 'evo::global.published', 'where' => [['published', 1]]],
                        ['value' => 'unpublished', 'icon' => 'eye-off', 'label' => 'evo::global.unpublished', 'where' => [['published', 0]]],
                    ],
                ],
            ],
            'columns' => [
                ['key' => 'id', 'field' => 'id', 'label' => 'ID', 'sortable' => true],
                ['key' => 'pagetitle', 'field' => 'pagetitle', 'label' => 'evo::global.column_pagetitle', 'cell' => 'resource-title', 'sortable' => true],
                ['key' => 'template', 'field' => 'templatename', 'relation' => 'tpl', 'sort_field' => 'template', 'label' => 'evo::global.column_template', 'empty' => '-', 'sortable' => true],
                ['key' => 'publishedon', 'field' => 'publishedon', 'label' => 'evo::global.column_publishedon', 'cell' => 'date', 'sortable' => true],
            ],
            'list' => [
                'title' => 'pagetitle',
                'subtitle' => 'template',
                'meta' => ['id', 'publishedon'],
            ],
            'row_actions' => [
                ['icon' => 'pencil', 'label' => 'evo::global.action_edit', 'url' => '?a=27&id={id}', 'tone' => 'primary', 'permission' => 'edit_document'],
                ['icon' => 'copy', 'label' => 'evo::global.action_copy', 'url' => '?a=94&id={id}', 'tone' => 'info', 'permission' => 'new_document'],
                ['icon' => 'trash', 'label' => 'evo::global.action_delete', 'url' => '?a=6&id={id}', 'tone' => 'danger', 'permission' => 'delete_document'],
            ],
        ],
    ],
    'forms' => [
        'site_content' => [
            'key' => 'site-content',
            'variant' => 'resource',
            'icon' => 'edit',
            'title' => 'evo::global.form_site_content',
            'title_field' => 'pagetitle',
            'meta_field' => 'id',
            'description' => 'evo::global.form_site_content_description',
            'include_tvs' => true,
            'multilingual' => [
                'enabled' => 'auto',
                'provider' => 'sLang',
                'fields' => ['pagetitle', 'longtitle', 'description', 'introtext', 'content', 'menutitle', 'seotitle', 'seodescription'],
                'tvs' => [],
            ],
            'tv_tab' => 'general',
            'tv_section_label' => 'evo::global.form_section_template_variables',
            'tabs' => [
                ['name' => 'general', 'label' => 'evo::global.form_tab_general', 'icon' => 'file-text'],
                ['name' => 'settings', 'label' => 'evo::global.form_tab_resource_settings', 'icon' => 'adjustments-horizontal'],
            ],
            'enabled_fields' => [
                'pagetitle',
                'longtitle',
                'description',
                'alias',
                'link_attributes',
                'introtext',
                'template',
                'menutitle',
                'menuindex',
                'hidemenu',
                'parent',
                'content',
                'published',
                'pub_date',
                'unpub_date',
                'type',
                'contentType',
                'content_dispo',
                'isfolder',
                'alias_visible',
                'richtext',
                'hide_from_tree',
                'searchable',
                'cacheable',
                '_syncsite',
                'privateweb',
                'privatemgr',
            ],
            'source' => [
                'type' => 'model',
                'model' => \EvolutionCMS\Models\SiteContent::class,
                'key' => 'id',
                'default' => 1,
            ],
            'save' => [
                'permission' => 'save_document',
            ],
            'actions' => [
                ['type' => 'link', 'icon' => 'file-plus', 'label' => 'evo::global.action_child_resource', 'url' => '?a=4&pid={id}', 'permission' => 'new_document'],
                ['type' => 'link', 'icon' => 'link-plus', 'label' => 'evo::global.action_child_weblink', 'url' => '?a=72&pid={id}', 'permission' => 'new_document'],
                ['type' => 'save', 'icon' => 'device-floppy', 'label' => 'evo::global.action_save', 'tone' => 'success', 'permission' => 'save_document'],
                ['type' => 'link', 'icon' => 'copy', 'label' => 'evo::global.action_copy', 'url' => '?a=94&id={id}', 'tone' => 'info', 'permission' => 'new_document'],
                ['type' => 'link', 'icon' => 'trash', 'label' => 'evo::global.action_delete', 'url' => '?a=6&id={id}', 'tone' => 'danger', 'permission' => 'delete_document'],
                ['type' => 'reset', 'icon' => 'rotate', 'label' => 'evo::global.action_cancel'],
                ['type' => 'link', 'icon' => 'eye', 'label' => 'evo::global.action_preview', 'url' => '../index.php?id={id}'],
            ],
            'sections' => [
                [
                    'key' => 'content',
                    'tab' => 'general',
                    'label' => 'evo::global.form_section_content',
                    'icon' => 'file-text',
                    'show_header' => false,
                    'fields' => [
                        ['name' => 'pagetitle', 'type' => 'text', 'label' => 'evo::global.field_pagetitle', 'rules' => ['required', 'string', 'max:255']],
                        ['name' => 'longtitle', 'type' => 'text', 'label' => 'evo::global.field_longtitle', 'rules' => ['nullable', 'string', 'max:255']],
                        ['name' => 'description', 'type' => 'text', 'label' => 'evo::global.field_description', 'rules' => ['nullable', 'string', 'max:255']],
                        ['name' => 'alias', 'type' => 'text', 'label' => 'evo::global.field_alias', 'rules' => ['nullable', 'string', 'max:255']],
                        ['name' => 'link_attributes', 'type' => 'text', 'label' => 'evo::global.field_link_attributes', 'rules' => ['nullable', 'string', 'max:255']],
                        ['name' => 'introtext', 'type' => 'textarea', 'label' => 'evo::global.field_introtext', 'rows' => 4, 'span' => 'full', 'rules' => ['nullable', 'string']],
                        ['name' => 'template', 'type' => 'select', 'label' => 'evo::global.field_template', 'span' => 'full', 'rules' => ['required', 'integer'], 'options_source' => [
                            'model' => \EvolutionCMS\Models\SiteTemplate::class,
                            'value' => 'id',
                            'label' => 'templatename',
                            'order_by' => [['templatename']],
                        ]],
                        ['name' => 'menutitle', 'type' => 'text', 'label' => 'evo::global.field_menutitle', 'rules' => ['nullable', 'string', 'max:255']],
                        ['name' => 'menuindex', 'type' => 'number', 'label' => 'evo::global.field_menuindex', 'size' => 'compact', 'min' => 0, 'rules' => ['nullable', 'integer', 'min:0']],
                        ['name' => 'hidemenu', 'type' => 'checkbox', 'label' => 'evo::global.field_show_in_menu', 'hint' => 'evo::global.enabled', 'invert' => true, 'rules' => ['boolean']],
                        ['name' => 'parent', 'type' => 'resource-parent', 'label' => 'evo::global.field_parent', 'display' => 'resource_parent', 'icon' => 'folder', 'rules' => ['required', 'integer', 'min:0']],
                        ['name' => 'content', 'type' => 'textarea', 'label' => 'evo::global.field_content', 'rows' => 5, 'span' => 'full', 'variant' => 'code', 'rules' => ['nullable', 'string']],
                    ],
                ],
                [
                    'key' => 'flags',
                    'tab' => 'settings',
                    'label' => 'evo::global.form_section_publication',
                    'icon' => 'calendar',
                    'span' => 6,
                    'fields' => [
                        ['name' => 'published', 'type' => 'checkbox', 'label' => 'evo::global.field_published', 'rules' => ['boolean']],
                        ['name' => 'pub_date', 'type' => 'datetime', 'label' => 'evo::global.field_pub_date', 'hint' => 'evo::global.datetime_hint', 'rules' => ['nullable']],
                        ['name' => 'unpub_date', 'type' => 'datetime', 'label' => 'evo::global.field_unpub_date', 'hint' => 'evo::global.datetime_hint', 'rules' => ['nullable']],
                    ],
                ],
                [
                    'key' => 'resource-options',
                    'tab' => 'settings',
                    'label' => 'evo::global.form_section_resource_options',
                    'icon' => 'adjustments-horizontal',
                    'span' => 6,
                    'fields' => [
                        ['name' => 'type', 'type' => 'select', 'label' => 'evo::global.field_resource_type', 'rules' => ['required', 'string'], 'options' => [
                            ['value' => 'document', 'label' => 'evo::global.resource_type_document'],
                            ['value' => 'reference', 'label' => 'evo::global.resource_type_reference'],
                        ]],
                        ['name' => 'contentType', 'type' => 'select', 'label' => 'evo::global.field_content_type', 'rules' => ['required', 'string'], 'options_source' => [
                            'type' => 'config_csv',
                            'key' => 'custom_contenttype',
                            'fallback' => 'text/html,text/plain,text/xml',
                        ]],
                        ['name' => 'content_dispo', 'type' => 'select', 'label' => 'evo::global.field_content_dispo', 'rules' => ['required', 'integer'], 'options' => [
                            ['value' => 0, 'label' => 'evo::global.content_dispo_inline'],
                            ['value' => 1, 'label' => 'evo::global.content_dispo_attachment'],
                        ]],
                        ['name' => 'isfolder', 'type' => 'checkbox', 'label' => 'evo::global.field_isfolder', 'rules' => ['boolean']],
                        ['name' => 'alias_visible', 'type' => 'checkbox', 'label' => 'evo::global.field_alias_visible', 'rules' => ['boolean']],
                        ['name' => 'richtext', 'type' => 'checkbox', 'label' => 'evo::global.field_richtext', 'rules' => ['boolean']],
                        ['name' => 'hide_from_tree', 'type' => 'checkbox', 'label' => 'evo::global.field_show_children', 'invert' => true, 'rules' => ['boolean']],
                        ['name' => 'searchable', 'type' => 'checkbox', 'label' => 'evo::global.field_searchable', 'rules' => ['boolean']],
                        ['name' => 'cacheable', 'type' => 'checkbox', 'label' => 'evo::global.field_cacheable', 'rules' => ['boolean']],
                        ['name' => '_syncsite', 'type' => 'checkbox', 'label' => 'evo::global.field_clear_cache', 'default' => true, 'save' => false],
                        ['name' => 'privateweb', 'type' => 'checkbox', 'label' => 'evo::global.field_privateweb', 'rules' => ['boolean']],
                        ['name' => 'privatemgr', 'type' => 'checkbox', 'label' => 'evo::global.field_privatemgr', 'rules' => ['boolean']],
                    ],
                ],
            ],
        ],
        'devo_ui_settings' => [
            'key' => 'evo-ui-settings',
            'variant' => 'config',
            'icon' => 'adjustments-horizontal',
            'title' => 'evo::global.form_settings',
            'description' => 'evo::global.form_settings_description',
            'tabs' => [
                ['name' => 'module', 'label' => 'evo::global.settings_tab_module', 'icon' => 'settings'],
                ['name' => 'table', 'label' => 'evo::global.settings_tab_table', 'icon' => 'table'],
                ['name' => 'form', 'label' => 'evo::global.settings_tab_form', 'icon' => 'forms'],
            ],
            'source' => [
                'type' => 'config',
                'file' => 'custom/config/evo-ui.php',
                'root' => 'evo-ui',
            ],
            'actions' => [
                ['type' => 'save', 'icon' => 'device-floppy', 'label' => 'evo::global.action_save', 'tone' => 'success'],
                ['type' => 'reset', 'icon' => 'rotate', 'label' => 'evo::global.action_cancel'],
            ],
            'sections' => [
                [
                    'key' => 'module',
                    'tab' => 'module',
                    'label' => 'evo::global.form_section_module',
                    'icon' => 'settings',
                    'fields' => [
                        ['name' => 'module.default_tab', 'type' => 'select', 'label' => 'evo::global.field_default_tab', 'config_key' => 'module.default_tab', 'hint' => 'evo::global.setting_default_tab_help', 'rules' => ['required', 'string'], 'options' => [
                            ['value' => 'table', 'label' => 'evo::global.table'],
                            ['value' => 'form', 'label' => 'evo::global.form'],
                            ['value' => 'layout', 'label' => 'evo::global.layout'],
                            ['value' => 'settings', 'label' => 'evo::global.settings'],
                        ]],
                    ],
                ],
                [
                    'key' => 'table',
                    'tab' => 'table',
                    'label' => 'evo::global.form_section_table_settings',
                    'icon' => 'table',
                    'fields' => [
                        ['name' => 'tables.site_content.per_page', 'type' => 'select', 'label' => 'evo::global.field_per_page_default', 'config_key' => 'tables.site_content.per_page', 'hint' => 'evo::global.setting_per_page_help', 'rules' => ['required', 'integer'], 'options' => [
                            ['value' => 5, 'label' => '5'],
                            ['value' => 10, 'label' => '10'],
                            ['value' => 20, 'label' => '20'],
                            ['value' => 50, 'label' => '50'],
                            ['value' => 100, 'label' => '100'],
                        ]],
                        ['name' => 'tables.site_content.default_view', 'type' => 'radio', 'label' => 'evo::global.field_default_view', 'config_key' => 'tables.site_content.default_view', 'hint' => 'evo::global.setting_default_view_help', 'rules' => ['required', 'string'], 'options' => [
                            ['value' => 'table', 'label' => 'evo::global.view_table'],
                            ['value' => 'list', 'label' => 'evo::global.view_list'],
                        ]],
                        ['name' => 'tables.site_content.enabled_columns', 'type' => 'multi-checkbox', 'label' => 'evo::global.field_table_columns', 'config_key' => 'tables.site_content.enabled_columns', 'hint' => 'evo::global.setting_table_columns_help', 'default' => ['id', 'pagetitle', 'template', 'publishedon'], 'rules' => ['array'], 'options' => [
                            ['value' => 'id', 'label' => 'ID'],
                            ['value' => 'pagetitle', 'label' => 'evo::global.column_pagetitle'],
                            ['value' => 'template', 'label' => 'evo::global.column_template'],
                            ['value' => 'publishedon', 'label' => 'evo::global.column_publishedon'],
                        ]],
                        ['name' => 'tables.site_content.enabled_filters', 'type' => 'multi-checkbox', 'label' => 'evo::global.field_table_filters', 'config_key' => 'tables.site_content.enabled_filters', 'hint' => 'evo::global.setting_table_filters_help', 'default' => ['templates', 'publishedon_range', 'kind', 'published'], 'rules' => ['array'], 'options' => [
                            ['value' => 'templates', 'label' => 'evo::global.filter_templates'],
                            ['value' => 'publishedon_range', 'label' => 'evo::global.filter_publication_date'],
                            ['value' => 'kind', 'label' => 'evo::global.filter_kind'],
                            ['value' => 'published', 'label' => 'evo::global.filter_published'],
                        ]],
                    ],
                ],
                [
                    'key' => 'form',
                    'tab' => 'form',
                    'label' => 'evo::global.form_section_form_settings',
                    'icon' => 'forms',
                    'fields' => [
                        ['name' => 'forms.site_content.source.default', 'type' => 'number', 'label' => 'evo::global.field_default_resource', 'config_key' => 'forms.site_content.source.default', 'hint' => 'evo::global.setting_default_resource_help', 'min' => 1, 'rules' => ['required', 'integer', 'min:1']],
                        ['name' => 'forms.site_content.enabled_fields', 'type' => 'multi-checkbox', 'label' => 'evo::global.field_form_fields', 'config_key' => 'forms.site_content.enabled_fields', 'hint' => 'evo::global.setting_form_fields_help', 'default' => [
                            'pagetitle',
                            'longtitle',
                            'description',
                            'alias',
                            'link_attributes',
                            'introtext',
                            'template',
                            'menutitle',
                            'menuindex',
                            'hidemenu',
                            'parent',
                            'content',
                            'published',
                            'pub_date',
                            'unpub_date',
                            'type',
                            'contentType',
                            'content_dispo',
                            'isfolder',
                            'alias_visible',
                            'richtext',
                            'hide_from_tree',
                            'searchable',
                            'cacheable',
                            '_syncsite',
                            'privateweb',
                            'privatemgr',
                        ], 'rules' => ['array'], 'options' => [
                            ['value' => 'pagetitle', 'label' => 'evo::global.field_pagetitle'],
                            ['value' => 'longtitle', 'label' => 'evo::global.field_longtitle'],
                            ['value' => 'description', 'label' => 'evo::global.field_description'],
                            ['value' => 'alias', 'label' => 'evo::global.field_alias'],
                            ['value' => 'link_attributes', 'label' => 'evo::global.field_link_attributes'],
                            ['value' => 'introtext', 'label' => 'evo::global.field_introtext'],
                            ['value' => 'template', 'label' => 'evo::global.field_template'],
                            ['value' => 'menutitle', 'label' => 'evo::global.field_menutitle'],
                            ['value' => 'menuindex', 'label' => 'evo::global.field_menuindex'],
                            ['value' => 'hidemenu', 'label' => 'evo::global.field_show_in_menu'],
                            ['value' => 'parent', 'label' => 'evo::global.field_parent'],
                            ['value' => 'content', 'label' => 'evo::global.field_content'],
                            ['value' => 'published', 'label' => 'evo::global.field_published'],
                            ['value' => 'pub_date', 'label' => 'evo::global.field_pub_date'],
                            ['value' => 'unpub_date', 'label' => 'evo::global.field_unpub_date'],
                            ['value' => 'type', 'label' => 'evo::global.field_resource_type'],
                            ['value' => 'contentType', 'label' => 'evo::global.field_content_type'],
                            ['value' => 'content_dispo', 'label' => 'evo::global.field_content_dispo'],
                            ['value' => 'isfolder', 'label' => 'evo::global.field_isfolder'],
                            ['value' => 'alias_visible', 'label' => 'evo::global.field_alias_visible'],
                            ['value' => 'richtext', 'label' => 'evo::global.field_richtext'],
                            ['value' => 'hide_from_tree', 'label' => 'evo::global.field_show_children'],
                            ['value' => 'searchable', 'label' => 'evo::global.field_searchable'],
                            ['value' => 'cacheable', 'label' => 'evo::global.field_cacheable'],
                            ['value' => '_syncsite', 'label' => 'evo::global.field_clear_cache'],
                            ['value' => 'privateweb', 'label' => 'evo::global.field_privateweb'],
                            ['value' => 'privatemgr', 'label' => 'evo::global.field_privatemgr'],
                        ]],
                    ],
                ],
            ],
        ],
    ],
];
